---
kind: Namespace
apiVersion: v1
metadata:
  name: dummy
  labels:
    name: dummy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-app-depl
  namespace: dummy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dummy-app
  template:
    metadata:
      labels:
        app: dummy-app
    spec:
      containers:
        - name: dummy-app
          image: busykoala/dummy_server:latest
          env:
          - name: DUMMY_SECRET
            value: not-a-very-secret-string
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
          - containerPort: 8000
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: dummy-app-svc
  namespace: dummy
spec:
  ports:
  - port: 80
    targetPort: 8000  # depl app port
    name: tcp
  selector:
    app: dummy-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dummy-app-ingress
  namespace: dummy
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dummy-app-svc
            port:
              number: 80
